apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: minote-mongodb
spec:
  volumes:
  - name: minote-mongo-vol
    persistentVolumeClaim:
      claimName: minote-storage
  containers:
  - image: mongo
    name: container1
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: minote-mongo-vol
      mountPath: /data/db